#!/usr/bin/env python3
"""
Render a styled schedule table PNG for a given list of events.
Usage: python3 render_table_image.py /tmp/calendar_table_full.png
This script will query events for next 7 days (via icalBuddy or calendar_read.py) and render an image.
"""
import os, subprocess
from PIL import Image, ImageDraw, ImageFont

OUT_PATH = '/tmp/calendar_table_full.png'
# gather events using icalBuddy eventsFrom:START to:END
try:
    start = subprocess.check_output(['date','+%Y-%m-%d'], text=True).strip()
    end = subprocess.check_output(['date','-v+7d','+%Y-%m-%d'], text=True).strip()
    raw = subprocess.check_output(['/opt/homebrew/bin/icalBuddy', f'eventsFrom:{start}', f'to:{end}'], text=True)
except Exception:
    # fallback to calendar_read.py
    try:
        raw = subprocess.check_output(['/usr/bin/env','python3','daily-schedule/calendar_read.py', start, end], text=True)
    except Exception:
        raw = ''

# parse raw into rows (simple split by double newline blocks)
items = [s.strip() for s in raw.split('\n\n') if s.strip()]
rows = []
for it in items:
    lines = it.splitlines()
    title = lines[0].lstrip('• ').strip()
    loc = ''
    time = ''
    for ln in lines[1:]:
        ln = ln.strip()
        if ln.startswith('location:'):
            loc = ln.replace('location:','').strip()
        else:
            # assume time line
            time = ln
    rows.append((time, title, loc))

# render image
w = 1100
row_h = 56
h = 140 + max(1, len(rows)) * row_h
img = Image.new('RGB',(w,h),(255,255,255))
d = ImageDraw.Draw(img)
# fonts
font_path = '/System/Library/Fonts/AppleSDGothicNeo.ttc'
try:
    font = ImageFont.truetype(font_path,18)
    bold = ImageFont.truetype(font_path,22)
    small = ImageFont.truetype(font_path,14)
except Exception:
    font = ImageFont.load_default()
    bold = font
    small = font
# header
d.rectangle([(0,0),(w,80)],fill=(18,88,159))
d.text((24,20),'다음 7일 일정',font=bold,fill=(255,255,255))
d.text((24,48), subprocess.check_output(['date','+%Y-%m-%d']).decode().strip() + ' 기준', font=small, fill=(235,235,235))
# table header
x = [24, 160, 740]
y0 = 100
d.rectangle([(12,y0-6),(w-12,y0+row_h-6)],fill=(240,240,240))
d.text((x[0],y0), '시간', font=bold, fill=(0,0,0))
d.text((x[1],y0), '제목', font=bold, fill=(0,0,0))
d.text((x[2],y0), '장소', font=bold, fill=(0,0,0))
# rows
for i,(time,title,loc) in enumerate(rows):
    yy = y0 + (i+1)*row_h
    if i % 2 == 0:
        d.rectangle([(12,yy-6),(w-12,yy+row_h-6)],fill=(250,250,250))
    # time (truncate)
    ttxt = time if len(time) < 40 else time[:37] + '...'
    d.text((x[0],yy), ttxt, font=font, fill=(40,40,40))
    # title
    t = title if len(title) < 60 else title[:57] + '...'
    d.text((x[1],yy), t, font=font, fill=(20,20,20))
    # location
    l = loc if len(loc) < 40 else loc[:37] + '...'
    d.text((x[2],yy), l, font=font, fill=(80,80,80))

# footer / branding
d.rectangle([(0,h-40),(w,h)],fill=(240,240,245))
d.text((24,h-30), 'Generated by Jarvis • 자동 일정표', font=small, fill=(80,80,90))

img.save(OUT_PATH)
print(OUT_PATH)
